### ISSUE TITLE
Aplikacja może uruchomić się na złym ekranie

### ISSUE THREAD

**Issue by jqdq** [mjukiewicz/Kogniliada#1]
# Co się dzieje?

Przy przypadkowo zamienionych numerach ekranów łatwo o uruchomienie jej na niepoprawnym ekranie (co potem trudno naprawić, gdyż ekran przykrywa konsolę, a z aplikacji nie można wyjść).
Dodatkowo taka sytuacja jest trudna do wykrycia, gdyż numery ekranów w UI zaczynają się od 1, a programowo od 0. Drugi ekran będzie więc, nieintuicyjnie, nazwany 1.

# Jak to naprawić?

```python
def select_display() -> int:
    try:
        val = int(input("numer ekranu: "))
    except ValueError:
        return 1
    else:
        return val

display_surface = pygame.display.set_mode((0, 0), pygame.FULLSCREEN, display=select_display())
```

**Comment by mjukiewicz** [comment]
fixed!
